### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.api#4]
Release to Maven Central

- [x] parent pom (2.2.0)
- [x] war parent pom (2.2.0)
- [x] groovy parent pom
- [x] org.anc.json.schema-compiler (1.3.0) used by the validator
- [x] org.anc.json.validator (1.1.2) used in serialization tests
- [x] api (no changes)
- [x] discriminators (2.3.3)
- [x] serialization (2.6.0)
- [x] vocabulary (~2.4.0~ 2.4.1)
- [x] metadata (1.3.0)
- [x] annotations (~1.3.0~ 1.3.1)
- [x] core (2.0.5)
- [x] client (~2.0.6~ 2.0.7)
- [ ] ~all (2.5.0)~

**Comment by ksuderman** [comment]
The org.lappsgrid.all package will have to stay at 2.5.0-SNAPSHOT until the deployment issues with Maven Central can be resolved.  However, everything else has been deployed so we will call this one done.
